// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZpg7KCG2JW_XmNG3vY2UtrHPfcPG_lc',
    appId: '1:1020750557862:web:2d49f9f235c3561ce4ba67',
    messagingSenderId: '1020750557862',
    projectId: 'wellness-6082a',
    authDomain: 'wellness-6082a.firebaseapp.com',
    storageBucket: 'wellness-6082a.appspot.com',
    measurementId: 'G-B5QNGWK7WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZxK1wviaZXxWrasXD2E8XlMWxM4H0buw',
    appId: '1:1020750557862:android:fa6e22d6cf2b64d0e4ba67',
    messagingSenderId: '1020750557862',
    projectId: 'wellness-6082a',
    databaseURL: 'https://wellness-6082a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wellness-6082a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmUN4nRrTqaif0fvZL5edpavBLtSQQO4',
    appId: '1:1020750557862:ios:6b5c360cba37c1f6e4ba67',
    messagingSenderId: '1020750557862',
    projectId: 'wellness-6082a',
    storageBucket: 'wellness-6082a.appspot.com',
    androidClientId: '1020750557862-ckoldbutt84nes8vtolnvhmhjojstq7u.apps.googleusercontent.com',
    iosClientId: '1020750557862-9vjiqpkjmago89ib04c8478joqmh7in2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmUN4nRrTqaif0fvZL5edpavBLtSQQO4',
    appId: '1:1020750557862:ios:e116e51f4e0cdef4e4ba67',
    messagingSenderId: '1020750557862',
    projectId: 'wellness-6082a',
    storageBucket: 'wellness-6082a.appspot.com',
    androidClientId: '1020750557862-ckoldbutt84nes8vtolnvhmhjojstq7u.apps.googleusercontent.com',
    iosClientId: '1020750557862-j3p0rf3trp0lojjhs0ffoi11u539ldco.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellness.RunnerTests',
  );
}